{% set name = "reduce" %}
{% set version = "4.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rlabduke/reduce/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 62e61cce221fff76b5834031302d91fe703a19945a42e16620d4fb860604daf4
  patches:
    - python.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make   # [not win]

test:
  commands:
    - test -f ${PREFIX}/bin/reduce  # [unix]
    - ${PREFIX}/bin/reduce || true  # [unix]

about:
  home: https://github.com/rlabduke/reduce
  summary: 'Reduce - tool for adding and correcting hydrogens in PDB files'
  description: |
    Reduce - tool for adding and correcting hydrogens in PDB files
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/rlabduke/reduce
  dev_url: https://github.com/rlabduke/reduce

extra:
  recipe-maintainers:
    - bkpoon
