azure:
  user_or_org: cctbx-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
github:
  user_or_org: phenix-project
  repo_name: reduce-feedstock
  branch_name: main
  tooling_branch_name: main
test: native
upload_on_branch: main
conda_build:
  pkg_format: '2'
  zstd_compression_level: 22
